require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
    - "app/**/*.rb"
    - "spec/**/*.rb"
    - "config/**/*.rb"
    - "Gemfile"
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
  TargetRubyVersion: 2.7.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - have_

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - lib/tasks/**/*.rake
    - config/routes.rb
    - config/environments/**/*.rb

Metrics/MethodLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
